#!/bin/bash

show_help() {
    echo "Usage: $0 <input_image> [output_prefix]"
    echo "Output: <output_prefix>.raw and <output_prefix>_data.h"
    echo "This tool converts images to 16-bit RGB565."
    exit 1
}

if [ "$#" -lt 1 ]; then show_help; fi

IN="$1"
PREFIX="${2:-image}"

RAW_OUT="${PREFIX}.raw"
HEADER_OUT="${PREFIX}_data.h"

TMP_DIR=$(mktemp -d)
trap 'rm -rf "$TMP_DIR"' EXIT

if [ ! -f "$IN" ]; then echo "Error: $IN not found"; exit 1; fi

# Get dimensions
W=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=noprint_wrappers=1:nokey=1 "$IN")
H=$(ffprobe -v error -select_streams v:0 -show_entries stream=height -of default=noprint_wrappers=1:nokey=1 "$IN")

if [ -z "$W" ] || [ -z "$H" ]; then
    echo "Error: Could not determine dimensions of $IN"
    exit 1
fi

echo "--- Converting image to RGB565 ---"
ffmpeg -v error -i "$IN" -f rawvideo -pix_fmt rgb565le -y "$TMP_DIR/raw.tmp"
if [ ! -f "$TMP_DIR/raw.tmp" ]; then
    echo "Error failed to convert image."
    exit 1
fi

echo "--- Assembling $RAW_OUT ---"
cat "$TMP_DIR/raw.tmp" > "$RAW_OUT"

echo "--- Generating $HEADER_OUT ---"
{
    echo "/* Automatically generated by img2fb.sh */"
    echo "#ifndef IMAGE_DATA_H"
    echo "#define IMAGE_DATA_H"
    echo "static const int image_width = $W;"
    echo "static const int image_height = $H;"
    echo "static const unsigned char image_raw[] = {"
    
    xxd -i < "$RAW_OUT"
    
    echo "};"
    echo "#endif"
} > "$HEADER_OUT"

echo "Done! Generated $RAW_OUT and $HEADER_OUT ($W x $H)."
